# Generated by Django 4.2.1 on 2023-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartUser',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Пользователь')),
                ('books', models.TextField(max_length=100, unique=True, verbose_name='Книги')),
            ],
        ),
    ]
