# Generated by Django 4.2.1 on 2023-05-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_cartuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartUser',
        ),
    ]
