# Generated by Django 4.2.1 on 2023-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_cartuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartuser',
            name='books',
            field=models.IntegerField(verbose_name='Книги'),
        ),
    ]
