# Generated by Django 4.2.1 on 2023-05-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='img',
            field=models.CharField(default=1, max_length=100, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
